name: Full Server Setup and Deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.key }}
      
      - name: SSH into server and set up environment
        env:
          SERVER_IP: 95.217.156.31
          SERVER_USER: root
          SECRET: ${{ secrets.secret }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          
          # Check and create missing folders
          FOLDERS=(
            "/mnt/HC_Volume_101598242/db-data"
            "/mnt/HC_Volume_101598242/logs"
            "/mnt/HC_Volume_101598242/redis-cache-data"
            "/mnt/HC_Volume_101598242/redis-queue-data"
            "/mnt/HC_Volume_101598242/sites"
          )
          
          for FOLDER in "${FOLDERS[@]}"; do
            if [ ! -d "$FOLDER" ]; then
              mkdir -p "$FOLDER"
              echo "Created folder: $FOLDER"
            else
              echo "Folder already exists: $FOLDER"
            fi
          done
          
          # Install Docker if it's not already installed
          if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
          fi
          
          # Install Docker Compose if it's not already installed
          if ! command -v docker-compose &> /dev/null; then
            curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          fi
          
          # Install NGINX if it's not already installed
          if ! command -v nginx &> /dev/null; then
            apt update && apt upgrade && apt-get install -y nginx
          fi
          
          # Clone the repository to /root/NACS_ERP
          if [ ! -d "/root/NACS_ERP" ]; then
            git clone https://$SECRET@github.com/dkhwaja/NACS_ERP.git /root/NACS_ERP
          else
            cd /root/NACS_ERP && git pull
          fi
          
          # Ensure the NGINX configuration directory exists
          NGINX_CONF_DIR="/root/NACS_ERP/nginx"
          if [ ! -d "$NGINX_CONF_DIR" ]; then
            mkdir -p "$NGINX_CONF_DIR"
            echo "Created NGINX configuration directory at $NGINX_CONF_DIR"
          fi
          
          # Check if the NGINX configuration file exists, copy it to sites-available if it does
          NGINX_CONF="$NGINX_CONF_DIR/proxy_to_localhost.conf"
          if [ -f "$NGINX_CONF" ]; then
            cp "$NGINX_CONF" /etc/nginx/sites-available/proxy_to_localhost.conf
            echo "Successfully copied NGINX configuration to /etc/nginx/sites-available/."
          else
            echo "NGINX configuration file not found at $NGINX_CONF."
            exit 1
          fi
          
          # Create symlink if it does not exist
          if [ ! -L "/etc/nginx/sites-enabled/proxy_to_localhost.conf" ]; then
            ln -sf /etc/nginx/sites-available/proxy_to_localhost.conf /etc/nginx/sites-enabled/
            echo "Created symlink for NGINX site."
          else
            echo "Symlink already exists."
          fi
          
          # Reload NGINX configuration
          nginx -s reload
          echo "NGINX reloaded successfully."
          
          # Change directory to project and run Docker Compose
          cd /root/NACS_ERP
          docker-compose -f pwd.yml down
          docker-compose -f pwd.yml up -d
          echo "Docker Compose started successfully."
          
          EOF
