name: Full Server Setup and Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.key }}
    
    - name: SSH into server and set up environment
      env:
        SERVER_IP: 37.27.33.129
        SERVER_USER: root
        GITHUB_TOKEN: ${{ secrets.secret }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          # Update and upgrade the package list
          apt-get update && apt-get upgrade -y

          # Install Docker if it's not already installed
          if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
          fi
          
          # Install Docker Compose if it's not already installed
          if ! command -v docker-compose &> /dev/null; then
            curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          fi

          # Install NGINX if it's not already installed
          if ! command -v nginx &> /dev/null; then
            apt-get install -y nginx
          fi

          # Clone the repository to /home/root/NACS_ERP
          if [ ! -d "/home/root/NACS_ERP" ]; then
              git clone https://$GITHUB_TOKEN@github.com/dkhawaja/NACS_ERP /root/NACS_ERP
          else
              cd /root/NACS_ERP && git pull
          fi

          # List files to check structure
          ls -la /root/NACS_ERP

          # Check if the NGINX configuration file exists, create if it does not
          if [ ! -f "/root/NACS_ERP/erpnext/nginx/proxy_to_localhost.conf" ]; then
              echo "NGINX configuration file not found! Creating default configuration."
              echo 'server {
                  listen 80;
                  server_name 37.27.33.129;

                  location / {
                      proxy_pass http://localhost:8080;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }
              }' > /root/NACS_ERP/erpnext/nginx/proxy_to_localhost.conf
          fi

          # Copy NGINX configuration to the sites-available directory
          cp /root/NACS_ERP/erpnext/nginx/proxy_to_localhost.conf /etc/nginx/sites-available/proxy_to_localhost.conf

          # Link to enable the site if it does not exist
          if [ ! -L "/etc/nginx/sites-enabled/proxy_to_localhost.conf" ]; then
              ln -sf /etc/nginx/sites-available/proxy_to_localhost.conf /etc/nginx/sites-enabled/
          fi

          # Reload NGINX configuration
          nginx -s reload

          # Change directory to project and run Docker Compose with specified file
          cd /root/NACS_ERP
          docker-compose -f pwd.yml up -d
        EOF
